// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptData(arg1:string):Promise<string>;

export function DecryptToBytes(arg1:string):Promise<Array<number>>;

export function EncryptBytes(arg1:Array<number>):Promise<string>;

export function EncryptData(arg1:string):Promise<string>;

export function GetEncryptionKeyBase64():Promise<string>;

export function Greet(arg1:string):Promise<string>;
