// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptData(arg1) {
  return window['go']['main']['App']['DecryptData'](arg1);
}

export function DecryptToBytes(arg1) {
  return window['go']['main']['App']['DecryptToBytes'](arg1);
}

export function EncryptBytes(arg1) {
  return window['go']['main']['App']['EncryptBytes'](arg1);
}

export function EncryptData(arg1) {
  return window['go']['main']['App']['EncryptData'](arg1);
}

export function GetEncryptionKeyBase64() {
  return window['go']['main']['App']['GetEncryptionKeyBase64']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
